:
  - "10"

after_script:
  
  - gitbook build

  - grunt upload
  - cd ./_book
  - git init
  - git config user.name "xuetinga"
  - git config user.email "1716237703@qq.com"
  - git add .
  - git commit -m "publish gitbook"i
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branches:
  only:
    - main
