
de_js:
  - "10"

after_script:
  
  - gitbook build

  - grunt upload
  - cd ./_book
  - git init
  - git config user.name "xuetinga"
  - git config user.email "1716237703@qq.com"
  - cp ../CNAME .
  - git add .
  - git commit -m "publish gitbook"
  - git push --force --quiet "https://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@github.com/xuetinga/TTBOOKS" master:${gh-pages}

branches:
  only:
    - main
